
import java.sql.ResultSetMetaData;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Administrator
 */
public class ProductOut extends javax.swing.JFrame {

    /**
     * Creates new form ProductOut
     */
    public ProductOut() {
        initComponents();
        Connection();
        ShopCombo();
        getProductsOut();
    }

    
    Connection con;
    PreparedStatement pst;
    DefaultTableModel df;
    int shopId;
    PreparedStatement pst1;
    PreparedStatement pst2;
    
    public void Connection(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stock","root","");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void ShopCombo(){
        try{
            pst = con.prepareStatement("select name from shop order by id desc");
            ResultSet rs = pst.executeQuery();
            shopCombo.removeAllItems();
            shopCombo.addItem("---Select a Shop---");
            while(rs.next()){
                shopCombo.addItem(rs.getString("name"));
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    public void getProductsOut(){
        int a;
        try{
            
            pst = con.prepareStatement("SELECT product_out.id,product_out.barcode,product.name,product_out.quantity,product_out.cost,product_out.total,shop.name,product_out.exit_date FROM product_out inner join product on product_out.barcode=product.barcode inner join shop on product_out.shop_id=shop.id order by product_out.id desc");
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rd = rs.getMetaData();
            a = rd.getColumnCount();
            df = (DefaultTableModel)ProductsOutTable.getModel();
            df.setRowCount(0);
            while(rs.next()){
                Vector v2 = new Vector();
                for(int i = 0; i < a; i++){
                    v2.add(rs.getString("id"));
                    v2.add(rs.getString("barcode"));
                    v2.add(rs.getString("product.name"));
                    v2.add(rs.getString("quantity"));
                    v2.add(rs.getString("cost"));
                    v2.add(rs.getString("total"));
                    v2.add(rs.getString("shop.name"));
                    v2.add(rs.getString("exit_date"));
                }
                df.addRow(v2);
            }
            
         }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        categoryMenuBtn = new javax.swing.JButton();
        suppliersMenuBtn = new javax.swing.JButton();
        productMenuBtn = new javax.swing.JButton();
        productInMenuBtn = new javax.swing.JButton();
        productOutMenuBtn = new javax.swing.JButton();
        reportMenuBtn = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        shopsMenuBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_ProductName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_cost = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_quantity = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        lbl_barcode = new javax.swing.JLabel();
        lbl_quantity = new javax.swing.JLabel();
        shopCombo = new javax.swing.JComboBox<>();
        txt_barcode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductsOutTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        categoryMenuBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        categoryMenuBtn.setText("Categories");
        categoryMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryMenuBtnActionPerformed(evt);
            }
        });

        suppliersMenuBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        suppliersMenuBtn.setText("Suppliers");
        suppliersMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliersMenuBtnActionPerformed(evt);
            }
        });

        productMenuBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productMenuBtn.setText("Product");
        productMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMenuBtnActionPerformed(evt);
            }
        });

        productInMenuBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productInMenuBtn.setText("Product In");
        productInMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productInMenuBtnActionPerformed(evt);
            }
        });

        productOutMenuBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productOutMenuBtn.setText("Product Out");
        productOutMenuBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 1, true));
        productOutMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productOutMenuBtnActionPerformed(evt);
            }
        });

        reportMenuBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reportMenuBtn.setText("Overview");
        reportMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportMenuBtnActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        shopsMenuBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        shopsMenuBtn.setText("Shops");
        shopsMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopsMenuBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(shopsMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(reportMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(categoryMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(suppliersMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productInMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productOutMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(reportMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(categoryMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(suppliersMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(shopsMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(productMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(productInMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(productOutMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));

        jLabel1.setText("Shop");

        jLabel2.setText("Barcode");

        jLabel3.setText("Product Name");

        txt_ProductName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_ProductName.setEnabled(false);

        jLabel4.setText("Cost");

        txt_cost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_cost.setEnabled(false);

        jLabel5.setText("Quantity");

        txt_quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_quantityKeyReleased(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        lbl_barcode.setForeground(new java.awt.Color(255, 0, 0));

        lbl_quantity.setForeground(new java.awt.Color(255, 0, 0));

        shopCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        shopCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopComboActionPerformed(evt);
            }
        });

        txt_barcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_barcodeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_barcodeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(shopCombo, 0, 176, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_barcode, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_cost, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_quantity)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_quantity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_barcode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(txt_ProductName)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(509, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_ProductName)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(shopCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(lbl_barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Products Out");

        ProductsOutTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Barcode", "Product Name", "Quantity", "Cost", "Total Cost", "Shop", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ProductsOutTable.setRowHeight(25);
        ProductsOutTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductsOutTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ProductsOutTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void suppliersMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliersMenuBtnActionPerformed
        // TODO add your handling code here:
        Supplier supplier = new Supplier();
        supplier.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_suppliersMenuBtnActionPerformed

    private void productMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMenuBtnActionPerformed
        // TODO add your handling code here:
        Product product = new Product();
        product.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_productMenuBtnActionPerformed

    private void productOutMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productOutMenuBtnActionPerformed
        // TODO add your handling code here:
        ProductOut productOut = new ProductOut();
        productOut.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_productOutMenuBtnActionPerformed

    private void shopsMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopsMenuBtnActionPerformed
        // TODO add your handling code here:
        Shops shop = new Shops();
        shop.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_shopsMenuBtnActionPerformed

    private void shopComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shopComboActionPerformed

    private void categoryMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryMenuBtnActionPerformed
        // TODO add your handling code here:
        Categories category = new Categories();
        category.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_categoryMenuBtnActionPerformed

    private void productInMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productInMenuBtnActionPerformed
        // TODO add your handling code here:
        ProductIn productIn = new ProductIn();
        productIn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_productInMenuBtnActionPerformed

    private void reportMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportMenuBtnActionPerformed
        // TODO add your handling code here:
        Report report = new Report();
        report.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reportMenuBtnActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void txt_barcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_barcodeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try{
                int barcode = Integer.parseInt(txt_barcode.getText());
                pst = con.prepareStatement("select * from product where barcode = ?");
                pst.setInt(1, barcode);
                ResultSet rs = pst.executeQuery();
                if(rs.next()){
                    txt_ProductName.setText(rs.getString("name"));
                    txt_cost.setText(rs.getString("cost"));
                    txt_quantity.requestFocus();
                }
                else{
                    JOptionPane.showMessageDialog(null, "No product with "+barcode+" barcode");
                    txt_barcode.setText("");
                    txt_ProductName.setText("");
                    txt_cost.setText("");
                    txt_quantity.setText("");
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_txt_barcodeKeyPressed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // ProductOut handling code
        
        if(txt_barcode.getText().trim().isEmpty() && txt_quantity.getText().trim().isEmpty()){
            lbl_barcode.setText("Barcode is required");
            lbl_quantity.setText("Quantity is required");
        }
         else if(shopCombo.getSelectedItem() == "---Select a Shop---" || txt_barcode.getText().trim().isEmpty() || txt_quantity.getText().trim().isEmpty()){
             JOptionPane.showMessageDialog(null, "Missing Information!!!.... Fill all fields before submit");
         }
        else{
            try {
                // TODO add your handling code here:
                LocalDateTime now = LocalDateTime.now();
                String created_at = DateTimeFormatter.ofPattern("yyyy-MM-dd").format(now);
                
                int cost = Integer.parseInt(txt_cost.getText());
                int quantity = Integer.parseInt(txt_quantity.getText());
                int total = cost * quantity;
                
                // getting shop id to insert it as foreign key from shop table
                pst1 = con.prepareStatement("select id from shop where name = ?");
                pst1.setString(1,shopCombo.getSelectedItem().toString());
                ResultSet rs1 = pst1.executeQuery();
                while(rs1.next()){
                    shopId = rs1.getInt("id");
                }
                
                
                 pst = con.prepareStatement("select *from product where barcode = ?");
                    pst.setString(1,txt_barcode.getText());
                    ResultSet rs3 = pst.executeQuery();
                    if(rs3.next()){ 
                        if(Integer.parseInt(rs3.getString("quantity")) >= quantity){
                            int newQuantity = Integer.parseInt(rs3.getString("quantity")) - quantity;
                            int newTotalCost = newQuantity * cost;
                        
                        

                        pst2 = con.prepareStatement("update product set quantity = ?, total_cost = ? where barcode = ?");
                        pst2.setInt(1,newQuantity);
                        pst2.setInt(2,newTotalCost);
                        pst2.setInt(3, Integer.parseInt(txt_barcode.getText()));
                        pst2.executeUpdate();
//                        if(){
//                            JOptionPane.showMessageDialog(null,"Quantity and cost is updated in products table");
//                        }
//                        else{
//                            JOptionPane.showMessageDialog(null,"Quantity and cost is not updated in products table");
//                        }
                        
                        pst = con.prepareStatement("insert into product_out (barcode,shop_id,quantity,cost,total,exit_date) values(?,?,?,?,?,?)");
                        pst.setString(1,txt_barcode.getText());
                        pst.setInt(2,shopId);
                        pst.setString(3,txt_quantity.getText());
                        pst.setString(4,txt_cost.getText());
                        pst.setInt(5,total);
                        pst.setString(6,created_at);
                        pst.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Products are Distributed successfully");
                        
                    }
                        else{
                            JOptionPane.showMessageDialog(null,"Quantity is not enough !!! Only "+rs3.getString("quantity")+" Pieces of "+rs3.getString("name")+" Remains");
                        }
                    }
                
                    getProductsOut();  

                    
                    txt_barcode.setText("");
                    txt_ProductName.setText("");
                    txt_cost.setText("");
                    txt_quantity.setText("");
                    txt_cost.setText("");
                    txt_barcode.requestFocus();
    //                getProducts();

                    lbl_barcode.setText("");
                    lbl_quantity.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void txt_barcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_barcodeKeyReleased
        // TODO add your handling code here:
        lbl_barcode.setText("");
    }//GEN-LAST:event_txt_barcodeKeyReleased

    private void txt_quantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_quantityKeyReleased
        // TODO add your handling code here:
        lbl_quantity.setText("");
    }//GEN-LAST:event_txt_quantityKeyReleased

    private void ProductsOutTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductsOutTableMouseClicked
        // TODO add your handling code here:
        df = (DefaultTableModel)ProductsOutTable.getModel();
        int selected = ProductsOutTable.getSelectedRow();
        int id = Integer.parseInt(df.getValueAt(selected,0).toString());
        txt_barcode.setText(df.getValueAt(selected, 1).toString());
        txt_ProductName.setText(df.getValueAt(selected, 2).toString());
        txt_quantity.setText(df.getValueAt(selected, 3).toString());
        txt_cost.setText(df.getValueAt(selected, 4).toString());
        saveBtn.setEnabled(false);
    }//GEN-LAST:event_ProductsOutTableMouseClicked

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        if(ProductsOutTable.getSelectedRow() >= 0){
        df = (DefaultTableModel)ProductsOutTable.getModel();
            int selected = ProductsOutTable.getSelectedRow();
            int id = Integer.parseInt(df.getValueAt(selected,0).toString());
            
            try {
                // TODO add your handling code here
                
                pst = con.prepareStatement("delete from product_out where id = ?");
                pst.setInt(1,id);
                
                
                int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this Product Out record", "Remove Product Out Record", JOptionPane.YES_NO_OPTION);
                if(confirm == JOptionPane.YES_OPTION){
                JOptionPane.showMessageDialog(null, "Record Deleted successfully","Remove Product Out Record",JOptionPane.INFORMATION_MESSAGE);
                pst.executeUpdate();
                txt_barcode.setText("");
                txt_ProductName.setText("");
                txt_cost.setText("");
                txt_quantity.setText("");
                txt_cost.setText("");
                txt_barcode.requestFocus();
                getProductsOut();
                saveBtn.setEnabled(true);
                
                lbl_barcode.setText("");
                lbl_quantity.setText("");
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Select a record to delete and continue");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ProductsOutTable;
    private javax.swing.JButton categoryMenuBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_barcode;
    private javax.swing.JLabel lbl_quantity;
    private javax.swing.JButton logout;
    private javax.swing.JButton productInMenuBtn;
    private javax.swing.JButton productMenuBtn;
    private javax.swing.JButton productOutMenuBtn;
    private javax.swing.JButton reportMenuBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JComboBox<String> shopCombo;
    private javax.swing.JButton shopsMenuBtn;
    private javax.swing.JButton suppliersMenuBtn;
    private javax.swing.JTextField txt_ProductName;
    private javax.swing.JTextField txt_barcode;
    private javax.swing.JTextField txt_cost;
    private javax.swing.JTextField txt_quantity;
    // End of variables declaration//GEN-END:variables
}
